### ISSUE TITLE
Archive doesn't work in dockers

### ISSUE THREAD

**Issue by dmks** [real-logic/aeron#605]
### My Purpose: 
I have one publisher and multiple subscribers, each of them is on different machines. I want to record the publisher's messages so that when a new subscriber comes, it could replay the message from the start (or from some specific position). 

### Setup:
I have following docker-compose.yml to simulate three machines:
```
version: "3.7"

networks:
  testing:
    ipam:
      config:
        - subnet: 172.21.0.0/24
services:
  engine:
    container_name: engine
    image: openjdk:10-jdk
    volumes:
      - ./:/code
      - ./data/engine:/dev/shm
    networks:
      testing:
        ipv4_address: 172.21.0.5
    command: tail -f /dev/null
    working_dir: /code/aeron-samples/scripts

  ws1:
    container_name: ws1
    image: openjdk:10-jdk
    volumes:
      - ./:/code
      - ./data/ws1:/dev/shm
    networks:
      testing:
        ipv4_address: 172.21.0.6
    command: tail -f /dev/null
    working_dir: /code/aeron-samples/scripts

  ws2:
    container_name: ws2
    image: openjdk:10-jdk
    volumes:
      - ./:/code
      - ./data/ws2:/dev/shm
    networks:
      testing:
        ipv4_address: 172.21.0.7
    command: tail -f /dev/null
    working_dir: /code/aeron-samples/scripts
```
Then I run 
```
$ docker-compose up -d
$ docker exec -it engine bash
root@5265cd18c54b:/code/aeron-samples/scripts# cd archive/
root@5265cd18c54b:/code/aeron-samples/scripts/archive# ./archiving-media-driver standard-archive.properties &
root@5265cd18c54b:/code/aeron-samples/scripts/archive# JVM_OPTS='-Daeron.sample.channel=aeron:udp?endpoint=224.0.1.1:40123' ./recorded-basic-publisher
Recording started: recordingId = 3
Offering 0/1000000 - yay!
Offering 1/1000000 - yay!
Offering 2/1000000 - yay!
Offering 3/1000000 - yay!
Offering 4/1000000 - yay!

# on the ws1 machine
$ docker exec -it ws1 bash
root@c61aebdbaa66:/code/aeron-samples/scripts# cd archive/
root@c61aebdbaa66:/code/aeron-samples/scripts/archive# ./archiving-media-driver standard-archive.properties &
JVM_OPTS='-Daeron.sample.channel=aeron:udp?endpoint=224.0.1.1:40123' ./replayed-basic-subscriber standard-archive.properties
```
### Problem 1:
Sometime the subscriber got the first M messages, and got stuck,  but the publisher is continously publishing messages. M is pretty random, could be 27, or 124, or whatever. 

### Problem 2:
Then if I restart the publisher, It will have a new recordingId, e.x recordingId = 4, 
Then if restart the subscriber, it will say the recordingId 4 is unknown

```
Exception in thread "main" io.aeron.archive.client.ArchiveException: response for correlationId=60, error: unknown recording id 4
	at io.aeron.archive.client.AeronArchive.pollForResponse(AeronArchive.java:1034)
	at io.aeron.archive.client.AeronArchive.startReplay(AeronArchive.java:609)
	at io.aeron.samples.archive.ReplayedBasicSubscriber.main(ReplayedBasicSubscriber.java:62)
```

BTW, I don't have any problem locally (But locally I only run one archive_media_driver)

### Additional Questions

1. Should I run archive_media_driver on every machine?
2. Where does the recording happen? on the publisher's media driver? or on the subscriber's media driver? 

Thanks,

BTW, I tested on master
